services:
    # gateways
    mailmotor.campaignmonitor.subscriber.gateway:
        class: MailMotor\Bundle\CampaignMonitorBundle\Gateway\CampaignMonitorSubscriberGateway
        arguments:
            - "%mailmotor.api_key%"
            - "%mailmotor.list_id%"
        tags:
            - { name: mailmotor.subscriber_gateway, alias: campaignmonitor }
