services:
    # gateways
    mailmotor.campaignmonitor.subscriber.gateway:
        class: MailMotor\Bundle\CampaignMonitorBundle\Gateway\CampaignMonitorSubscriberGateway
        arguments:
            - "%mailmotor.api_key%"
